### ISSUE TITLE
How to preprocess the data?

### ISSUE THREAD

**Issue by BorHon** [xxxliu95/DGNet#1]
Hi!
Thanks for sharing! I have downloaded the datasets but I don't know how to preprocess them. Could you please upload the data preprocess code? Thanks in advance.

**Comment by xxxliu95** [comment]
Hi,

Thanks for your interest. I have uploaded the preprocess scripts for both datasets used in this project.

They are in proprecess/.

Best wishes,
Xiao

**Comment by zhuangyi1** [comment]
> Hi! Thanks for sharing! I have downloaded the datasets but I don't know how to preprocess them. Could you please upload the data preprocess code? Thanks in advance.
大佬 我预处理代码老是不成功 可以请教一下吗 我qq是271224431 拜托！
