### ISSUE TITLE
How to generate the Re directory?

### ISSUE THREAD

**Issue by BorHon** [xxxliu95/DGNet#3]
Thanks for sharing and answering my questions.

I have ran the data preprocess code, but I still can not generate the ReA_dir for training.  Could you  please also share this part of code? Or could you please tell me how to deal with this directory for training?

Thanks in advance.

**Comment by BorHon** [comment]
It is the mnms_split_2D_re directory I don't know how to generate it.

**Comment by xxxliu95** [comment]
Oh, I forgot about this.

I just uploaded the resolution extracting code in the preprocess folder.
