### ISSUE TITLE
How many times an experiment will be repeated?

### ISSUE THREAD

**Issue by nekomiao123** [xxxliu95/DGNet#7]
I noticed that there was always a big deviation in the table. And I could not find how many times an experiment would be repeated in the paper. So I want to ask about this question.

**Comment by xxxliu95** [comment]
Hi, thanks for the question.

We only performed 1-run experiment for each case i.e. we did not repeat the experiments as there were already many cases.

The deviation is the variance across predictions on different patients. You can see this in inference.py.

Best wishes,
Xiao

**Comment by nekomiao123** [comment]
Got it. Thank you very much.
