### ISSUE TITLE
How do you calculate hausdorff distance?

### ISSUE THREAD

**Issue by nekomiao123** [xxxliu95/DGNet#9]
I noticed that you use the hausdorff distance as one of the metrics. But I could not find your code about calculating this distance. So I tried to use the scipy library to calculate. I found that the results are quite different. I always get larger results than the results given in the paper. So could you show me the code?

**Comment by xxxliu95** [comment]
Hi code updated. Please find the calculation in inference.py. The parameters in the current version are not tuned hence the distance is larger. Please see the discussion in another issue. I will update the training soon.
